import edu.rit.ds.RemoteEvent;

/**
 * Class GPSOfficeevent is a type of RemoteEvent that is generated by the
 * GPSOffice object in the Geographic Package System. These events correspond to
 * the notifications of the arrival, departure, delivery and loss of a package
 * while transportation.
 * 
 * @author Chinmay Dani
 * 
 */
public class GPSOfficeEvent extends RemoteEvent {
	private static final long serialVersionUID = 1L;
	/**
	 * A receipt object that contains the destination location and the track
	 * number of a package.
	 */
	private final Receipt receipt;
	/**
	 * The GPS office that generated this event.
	 */
	private String currentOffice;
	/**
	 * A flag to indicate if the package was lost.
	 */
	private boolean lost = false;
	/**
	 * A flag to indicate if the package was delivered to the destination.
	 */
	private boolean isDelivered = false;
	/**
	 * A flag to indicate if the package has arrived to or left the GPS office.
	 */
	private boolean arrived = false;

	/**
	 * Construct a new GPSOfficeEvent object.
	 * 
	 * @param receipt
	 *            A receipt object.
	 * @param name
	 *            Name of the GPSOffice that generated the event.
	 * @param lost
	 *            Indicates package loss status.
	 * @param isDelivered
	 *            Indicates package delivery status.
	 * @param arrived
	 *            Indicates package arrival/departure status.
	 */
	public GPSOfficeEvent(Receipt receipt, String name, boolean lost,
			boolean isDelivered, boolean arrived) {
		this.receipt = receipt;
		this.currentOffice = name;
		this.lost = lost;
		this.isDelivered = isDelivered;
		this.arrived = arrived;
	}

	/**
	 * Indicates whether a package was lost.
	 * 
	 * @return packageLossStatus
	 */
	public boolean isLost() {
		return lost;
	}

	/**
	 * Returns the name of the GPSOffice object.
	 * 
	 * @return the name of the GPSOffice object.
	 */
	public String getCurrentOffice() {
		return currentOffice;
	}

	/**
	 * Indicates whether a package was delivered.
	 * 
	 * @return packageDeliveryStatus
	 */
	public boolean isDelivered() {
		return isDelivered;
	}

	/**
	 * Indicates whether a package was arrived/departed.
	 * 
	 * @return packageArrivalOrDepartureStatus
	 */
	public boolean isArrived() {
		return arrived;
	}

	/**
	 * Returns the receipt info of the package.
	 * 
	 * @return the receipt info of the package.
	 */
	public Receipt getReceipt() {
		return receipt;
	}

}
